version: '2.2'
services:
  auth-microservice:
    ports:
      - "8080:8080"
    image: coursework
    container_name: coursework-container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - local.env
    volumes:
      - "./maven-rep:/root/.m2"


  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      local.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5